"""add more analytics_fields

Revision ID: 2682f4b45c8b
Revises: add_analytics_fields
Create Date: 2025-05-01 22:12:31.891960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2682f4b45c8b'
down_revision: Union[str, None] = 'add_analytics_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('line_items', sa.Column('total_discount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('line_items', sa.Column('tax_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('line_items', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('line_items', sa.Column('fulfillment_status', sa.String(length=50), nullable=True))

    op.add_column('line_items', sa.Column('requires_shipping', sa.Boolean(), nullable=True))
    op.add_column('line_items', sa.Column('gift_card', sa.Boolean(), nullable=True))
    op.add_column('line_items', sa.Column('taxable', sa.Boolean(), nullable=True))

    op.execute("UPDATE line_items SET requires_shipping = FALSE")
    op.execute("UPDATE line_items SET gift_card = FALSE")
    op.execute("UPDATE line_items SET taxable = FALSE")

    op.alter_column('line_items', 'requires_shipping', nullable=False)
    op.alter_column('line_items', 'gift_card', nullable=False)
    op.alter_column('line_items', 'taxable', nullable=False)



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_items', 'taxable')
    op.drop_column('line_items', 'gift_card')
    op.drop_column('line_items', 'requires_shipping')
    op.drop_column('line_items', 'fulfillment_status')
    op.drop_column('line_items', 'properties')
    op.drop_column('line_items', 'tax_lines')
    op.drop_column('line_items', 'total_discount')
    # ### end Alembic commands ###
