"""create product variant

Revision ID: 2840cfa136d7
Revises: 289e45fcfe9d
Create Date: 2025-05-03 20:41:31.143492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2840cfa136d7'
down_revision: Union[str, None] = '289e45fcfe9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('platform_variant_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('compare_at_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.String(length=100), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('option1', sa.String(length=255), nullable=True),
    sa.Column('option2', sa.String(length=255), nullable=True),
    sa.Column('option3', sa.String(length=255), nullable=True),
    sa.Column('taxable', sa.Boolean(), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('image_id', sa.String(length=100), nullable=True),
    sa.Column('platform_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('platform_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'platform_variant_id', name='uq_product_platform_variant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_variants')
    # ### end Alembic commands ###
