"""add currency in store

Revision ID: 289e45fcfe9d
Revises: 2682f4b45c8b
Create Date: 2025-05-03 12:40:52.411031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289e45fcfe9d'
down_revision: Union[str, None] = '2682f4b45c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('currency', sa.String(length=3), nullable=True))

    op.execute("UPDATE stores SET currency = 'SAR'")
    op.alter_column('stores', 'currency', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'currency')
    # ### end Alembic commands ###
