"""create DailySalesAnalytics table

Revision ID: 7de9555d0b5b
Revises: 80238d16f2e9
Create Date: 2025-05-16 10:06:22.331391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de9555d0b5b'
down_revision: Union[str, None] = '80238d16f2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_orders', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('average_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id', 'date'),
    postgresql_partition_by='RANGE (date)'
    )
    op.create_index('idx_store_date', 'daily_sales_analytics', ['store_id', 'date'], unique=False)
    op.create_index(op.f('ix_daily_sales_analytics_date'), 'daily_sales_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_daily_sales_analytics_store_id'), 'daily_sales_analytics', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_sales_analytics_store_id'), table_name='daily_sales_analytics')
    op.drop_index(op.f('ix_daily_sales_analytics_date'), table_name='daily_sales_analytics')
    op.drop_index('idx_store_date', table_name='daily_sales_analytics')
    op.drop_table('daily_sales_analytics')
    # ### end Alembic commands ###
